blank_issues_enabled: false
contact_links:
  - name: ğŸ¤ Team Notion
    url: https://www.notion.so/Github-c3875ca9f2b946e19f32ec47ff85a719#98f71c5d5f4e43d29a696a2502f75a51
    about: ì´ìŠˆ ìƒì„±ê³¼ ì»¤ë°‹ì»¨ë²¤ì…˜ì— ê´€í•œ ë¬¸ì„œ
  - name: ğŸ­ Team Jira
    url: https://gksdygks359-1727150204255.atlassian.net/jira/software/projects/KAN/boards/1
    about: Jira í”„ë¡œì íŠ¸ ê´€ë¦¬ë„êµ¬ í•«ë§í¬
