blank_issues_enabled: false
contact_links:
  - name: ğŸ¤ Team Notion
    url: https://www.notion.so/goormkdx/19-e0ba129775394d8baff8b345f4d63876
    about: 19ì¡° íŒ€ ë…¸ì…˜
  - name: ğŸ­ Team Jira
    url: https://gksdygks359-1727150204255.atlassian.net/jira/software/projects/KAN/boards/1
    about: Jira í”„ë¡œì íŠ¸ ê´€ë¦¬ë„êµ¬ í•«ë§í¬
